export const banks = [
    {"value": "Access Bank" ,"label":"Access Bank" },
    {"value": " Access Bank (Diamond)","label":" Access Bank (Diamond)" },
    {"value": " ALAT by WEMA","label":" ALAT by WEMA" },
    {"value": "  ASO Savings and Loans","label":"ASO Savings and Loans" },
    {"value": "  Bowen Microfinance Bank","label": "Bowen Microfinance Bank" },
    {"value": "  CEMCS Microfinance Bank","label": "CEMCS Microfinance Bank" },
    {"value": "Citibank","label":"Citibank" },
    {"value": "  Coronation Merchant Bank","label": "Coronation Merchant Bank" },
    { "value": "Dynamic Standard Bank", "label" :"Dynamic Standard Bank"},
    { "value": "Ecobank Nigeria","label":"Ecobank Nigeria" },
    { "value": "Fidelity Bank Nigeria","label":"Fidelity Bank Nigeria" },
    { "value": "Firmus MFB","label":"Firmus MFB" },
    { "value": "First Bank of Nigeria","label":"First Bank of Nigeria" },
    { "value": "First City Monument Bank","label":"First City Monument Bank" },
    { "value": "FSDH Merchant Bank Limited","label":"FSDH Merchant Bank Limited" },
    { "value": "Globus Bank","label":"Globus Bank" },
    {"value": "Guaranty Trust Bank","label":"Guaranty Trust Bank" },
    {"value": "Hackman Microfinance Bank","label":"Hackman Microfinance Bank" },
    {"value": "Hasal Microfinance Bank","label":"Hasal Microfinance Bank" },
    { "value": "Heritage Bank Plc","label":"Heritage Bank Plc" },
    { "value": "Infinity MFB","label":"Infinity MFB" },
    { "value": "Jaiz Bank","label":"Jaiz Bank" },
    { "value": "Keystone Bank Limited","label":"Keystone Bank Limited" },
    { "value": "Kuda Bank","label":"Kuda Bank" },
    { "value": "Lagos Building Investment Company Plc.","label":"Lagos Building Investment Company Plc." },
    { "value": "PalmPay","label":"PalmPay" },
    { "value": "Petra Mircofinance Bank Plc","label":"Petra Mircofinance Bank Plc" },
    { "value": "Providus Bank Plc","label":"Providus Bank Plc" },
    {"value": "Polaris Bank","label":"Polaris Bank" },
    {"value": " Rand Merchant Bank","label":" Rand Merchant Bank" },
    {"value": "Rubies MFB","label":"Rubies MFB" },
    {"value": "Sparkle Microfinance Bank","label":"Sparkle Microfinance Bank" },
    { "value": "Stanbic IBTC Bank Nigeria Limited","label":"Stanbic IBTC Bank Nigeria Limited" },
    { "value": "Standard Chartered Bank","label":"Standard Chartered Bank" },
    { "value": "Sterling Bank","label":"Sterling Bank" },
    { "value": "Suntrust Bank Nigeria Limited","label":"Suntrust Bank Nigeria Limited" },
    { "value": "Titan Bank","label":"Titan Bank" },
    { "value": "Union Bank of Nigeria","label":"Union Bank of Nigeria" },
    { "value": "United Bank for Africa","label":"United Bank for Africa" },
    {  "value": "Unity Bank Plc","label":"Unity Bank Plc" },
    {  "value": "VFD Microfinance Bank Limited","label":"VFD Microfinance Bank Limited" },
    { "value": "Wema Bank","label":"Wema Bank" },
    { "value": "Zenith Bank","label":"Zenith Bank" }
  ];